// Generated by weightlifting scraper
// Last updated: 2025-03-05T18:17:35.419Z

export interface LiftResult {
    lifter: string;
    bodyWeight: number;
    snatch: number;
    cj: number;
    total: number;
}

export const liftingResults: LiftResult[] = [
  { lifter: "Christina Quaile", bodyWeight: 80.08, snatch: 55, cj: 80, total: 135 }
];
